<a href="https://colab.research.google.com/github/thisshashank/PWassignment/blob/main/numpy_assignment_30_spt_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ------------------------Theory-----------------------------------------

# 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

NumPy (Numerical Python) is a core library for scientific computing and data analysis in Python. It provides powerful tools for working with large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.

Purpose:
1. Efficient array handling: Provides a high-performance multidimensional array object (ndarray).

2. Mathematical operations: Supports a wide range of mathematical operations on arrays (e.g., element-wise operations, matrix multiplication).
3. Interfacing with C/C++: Allows for integration with lower-level languages, enabling faster computation.

Advantages:

a. Speed: NumPy operations are faster than native Python operations due to vectorization, avoiding Python loops.
b. Memory efficiency: Handles large datasets using less memory.
c. Broad functionality: Offers support for random number generation, Fourier transforms, and linear algebra routines.
D. Interoperability: Integrates well with other libraries like pandas, SciPy, and matplotlib, enhancing the ecosystem for data analysis.
By extending Python’s capabilities for numerical tasks, NumPy makes it suitable for high-performance computing and data manipulation.








# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Comparison:
1. np.mean(): Calculates the arithmetic mean (average) of the array elements. It treats all values equally.
2. np.average(): Similar to np.mean(), but allows specifying weights for each element, providing a weighted average.
Contrast:
1. Weights: np.mean() doesn’t support weights, while np.average() does.
2. Use case: Use np.mean() for a simple average and np.average() when you need to account for weights.

When to use:
1. np.mean(): For equal importance of all data points.
2. np.average(): When certain data points should have more influence on the result (weighted average).

# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.


Methods for Reversing a NumPy Array:
1. For 1D array:
Use slicing: [::-1]

In [ ]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4])
reversed_1d = arr_1d[::-1]
print(reversed_1d)  # Output: [4, 3, 2, 1]


[4 3 2 1]


For 2D array:

Reverse rows (axis 0): [::-1, :]
Reverse columns (axis 1): [:, ::-1]
Reverse both: [::-1, ::-1]

In [ ]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
reverse_rows = arr_2d[::-1, :]
reverse_cols = arr_2d[:, ::-1]
reverse_both = arr_2d[::-1, ::-1]


# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

we can determine the data type of elements in a NumPy array using the .dtype attribute.

In [ ]:
arr = np.array([1, 2, 3])
print(arr.dtype)

# Importance of Data Types:
a. Memory management: NumPy allows control over memory usage by specifying    b. data types. For example, using int8 instead of int64 reduces memory consumption when working with small integers.
c. Performance: Proper data types improve performance. Smaller or simpler data types (like float32 vs float64) allow faster computations and reduce memory overhead, which is crucial for large datasets.

# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ndarray (N-dimensional array):
In NumPy, an ndarray is a multidimensional, homogeneous array of fixed-size data elements, all of the same type.

Key Features:
1. Homogeneous: All elements have the same data type.
2. Efficient Memory: Stored in contiguous blocks of memory, improving speed and efficiency.
3. Supports Vectorized Operations: Operations on arrays are faster due to element-wise computation without explicit loops.
4. Multidimensional: Supports multi-dimensional arrays (1D, 2D, etc.).
5. Broadcasting: Allows operations on arrays of different shapes without       extensive reshaping.

Differences from Python Lists:
Data Type: Lists can store mixed data types, while ndarray is homogeneous.
Performance: `nd

# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

Performance Benefits of NumPy Arrays over Python Lists:
Speed: NumPy arrays are much faster than Python lists due to optimized, compiled C code and support for vectorized operations, which eliminate loops.

Example: Element-wise operations on arrays are performed in parallel, whereas Python lists require explicit iteration.
Memory Efficiency: NumPy arrays use less memory by storing elements in contiguous memory blocks and using fixed data types (e.g., int32, float64), unlike Python lists which store heterogeneous types with higher overhead.

Vectorization: NumPy operations are vectorized, meaning mathematical operations on arrays are executed in bulk rather than element by element, significantly speeding up computations.

Built-in functions: NumPy offers a wide array of optimized mathematical functions for array operations, making it ideal for large-scale numerical computations.

Overall, NumPy provides better performance, particularly for large datasets, due to optimized memory usage and faster execution.

# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.


Comparison:
vstack(): Stacks arrays vertically (row-wise). Use vstack() to stack arrays row-wise, resulting in a 2D array.



In [ ]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
result_v = np.vstack((arr1, arr2))
print(result_v)
# Output:
# [[1 2]
#  [3 4]]


hstack(): Stacks arrays horizontally (column-wise). Use hstack() to stack arrays column-wise, resulting in a single row (or wider array).

In [ ]:
result_h = np.hstack((arr1, arr2))
print(result_h)
# Output:
# [1 2 3 4]


# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

Differences Between fliplr() and flipud() in NumPy:
1. fliplr() (Flip Left-Right):

a. Reverses the elements horizontally (left to right) along the second axis (axis 1).
b. Only works on 2D or higher-dimensional arrays.
c. Effect: Columns are reversed.

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
result = np.fliplr(arr)
print(result)
# Output:
# [[2 1]
#  [4 3]
#  [6 5]]


flipud() (Flip Up-Down):

a. Reverses the elements vertically (top to bottom) along the first axis (axis 0).
b. Works on both 1D and multi-dimensional arrays.
c. Effect: Rows are reversed.

In [ ]:
result = np.flipud(arr)
print(result)
# Output:
# [[5 6]
#  [3 4]
#  [1 2]]


# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Functionality of array_split() in NumPy:
array_split() splits an array into specified sections along a given axis. Unlike split(), it can handle uneven splits.

Handling Uneven Splits:
When the array doesn't divide evenly by the number of sections, array_split() ensures that smaller sub-arrays are created. It distributes the leftover elements across the first few sections.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
result = np.array_split(arr, 3)
print(result)



# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

# Vectorization:
Definition: Vectorization is the process of applying operations to entire arrays (or "vectors") without explicit loops.
Efficiency: It leverages low-level optimizations in NumPy (C-based) for faster computations by avoiding Python's slower loops.

In [ ]:
arr = np.array([1, 2, 3])
result = arr * 2


# Broadcasting:
Definition: Broadcasting allows NumPy to perform operations on arrays of different shapes by "stretching" the smaller array to match the dimensions of the larger one.
Efficiency: It avoids memory duplication and reduces computation time by applying operations element-wise on arrays with different shapes.


In [ ]:
arr = np.array([1, 2, 3])
result = arr + 5  # Adds 5 to each element
# Output: [6, 7, 8]


# Contribution to Efficiency:
Vectorization eliminates loops, speeding up operations.
Broadcasting reduces memory usage and allows for flexible, element-wise operations on arrays with differing shapes. Together, they make array operations in NumPy faster and more memory-efficient.







# --------------------------------Practical Questions:-----------------------------------

# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [ ]:
import numpy as np

arr = np.random.randint(1, 101, size=(3, 3))


transposed_arr = arr.T

arr, transposed_arr


(array([[79, 43, 97],
        [78, 54, 79],
        [94, 34, 67]]),
 array([[79, 78, 94],
        [43, 54, 34],
        [97, 79, 67]]))

# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

# Generate a 1D NumPy array with 10 elements
arr_1d = np.arange(10)

# Reshape into a 2x5 array
arr_2x5 = arr_1d.reshape(2, 5)

# Reshape into a 5x2 array
arr_5x2 = arr_1d.reshape(5, 2)

arr_1d, arr_2x5, arr_5x2


# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [ ]:
import numpy as np

# Create a 4x4 array with random float values
original_array = np.random.rand(4, 4)

# Add a border of zeros
bordered_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 Array:")
print(original_array)

print("\n6x6 Array with Zero Border:")
print(bordered_array)


Original 4x4 Array:
[[0.43095747 0.93623664 0.10633015 0.56484775]
 [0.96108995 0.71008973 0.98400858 0.03103956]
 [0.00576692 0.14735936 0.31429749 0.461017  ]
 [0.12054093 0.09091569 0.13247013 0.14809387]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.43095747 0.93623664 0.10633015 0.56484775 0.        ]
 [0.         0.96108995 0.71008973 0.98400858 0.03103956 0.        ]
 [0.         0.00576692 0.14735936 0.31429749 0.461017   0.        ]
 [0.         0.12054093 0.09091569 0.13247013 0.14809387 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

print(array)


# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [ ]:
import numpy as np

# Create an array of strings
strings = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(strings)
lowercase = np.char.lower(strings)
titlecase = np.char.title(strings)
capitalize = np.char.capitalize(strings)

# Print the results
print("Original Array:")
print(strings)

print("\nUppercase:")
print(uppercase)

print("\nLowercase:")
print(lowercase)

print("\nTitle Case:")
print(titlecase)

print("\nCapitalized:")
print(capitalize)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalized:
['Python' 'Numpy' 'Pandas']


# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
import numpy as np

# Create an array of words
words = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

# Print the results
print("Original Array:")
print(words)

print("\nWords with Spaces Between Characters:")
for word in spaced_words:
    print(word)


# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [ ]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                    [10, 11, 12]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
division = array1 / array2

# Print the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Print the results
print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

In [ ]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Find all prime numbers in the array
prime_numbers = np.array([num for num in random_integers if is_prime(num)])

# Print the results
print("Random Integers Array:")
print(random_integers)

print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Integers Array:
[541 532 282 737 353 986 165 459 741 408 570 248 140 549 631   3 970 120
 709 671 958 360 386  62  51 120 700 473 526 118  40 500  27 126 315 905
 631 234 300 208 248 482 537 667 939 985 707  29 143 560 144 506  92 879
 699 611 271 538  78 271 500 813 803 113 593 249 324 190 413 648 822 825
 530 208 742 933 395 868 191 150 222 841 724 628 252 234 652 933 979 969
 782 564 870 511 601 880 301 724 509 140]

Prime Numbers in the Array:
[541 353 631   3 709 631  29 271 271 113 593 191 601 509]


# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

In [ ]:
import numpy as np

daily_temperatures = np.random.randint(0, 36, size=30)
weekly_averages = []
for i in range(0, 30, 7):
    weekly_avg = daily_temperatures[i:i+7].mean()
    weekly_averages.append(weekly_avg)

print("Daily Temperatures for the Month:")
print(daily_temperatures)

print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for the Month:
[15  3 13 11 28  4 26  2  8 18  8 23 34  0  5 15 11  2 22 14 25 33 33 21
 34  5 32 18 11 17]

Weekly Averages:
[14.285714285714286, 13.285714285714286, 13.428571428571429, 25.142857142857142, 14.0]
